
VNINDEX = ['AAA', 'AAM', 'AAT', 'ABR', 'ABS', 'ABT', 'ACB', 'ACC', 'ACG', 'ACL', 'ADG', 'ADP', 'ADS', 'AGG',
            'AGM', 'AGR', 'ANV', 'APG', 'APH', 'ASG', 'ASM', 'ASP', 'AST', 'ATP', 'BAF', 'BBC', 'BCE', 'BCG',
            'BCM', 'BFC', 'BHN', 'BIC', 'BID', 'BKG', 'BMC', 'BMI', 'BMP', 'BRC', 'BSI', 'BSR', 'BTP', 'BTT',
            'BVH', 'BWE', 'C32', 'C47', 'CCI', 'CCL', 'CDC', 'CHP', 'CIG', 'CII', 'CKG', 'CLC', 'CLL', 'CLW',
            'CMG', 'CMV', 'CMX', 'CNG', 'COM', 'CRC', 'CRE', 'CRV', 'CSM', 'CSV', 'CTD', 'CTF', 'CTG', 'CTI',
            'CTR', 'CTS', 'CVT', 'D2D', 'DAH', 'DAT', 'DBC', 'DBD', 'DBT', 'DC4', 'DCL', 'DCM', 'DGC', 'DGW',
            'DHA', 'DHC', 'DHG', 'DHM', 'DIG', 'DLG', 'DMC', 'DPG', 'DPM', 'DPR', 'DQC', 'DRC', 'DRH', 'DRL',
            'DSC', 'DSE', 'DSN', 'DTA', 'DTL', 'DTT', 'DVP', 'DXG', 'DXS', 'DXV', 'E1VFVN30', 'EIB', 'ELC', 'EVE',
            'EVF', 'EVG', 'FCM', 'FCN', 'FDC', 'FIR', 'FIT', 'FMC', 'FPT', 'FRT', 'FTS', 'FUCTVGF3', 'FUCTVGF4',
            'FUCTVGF5', 'FUCVREIT', 'FUEABVND', 'FUEBFVND', 'FUEDCMID', 'FUEFCV50', 'FUEIP100', 'FUEKIV30', 'FUEKIVFS',
            'FUEKIVND', 'FUEMAV30', 'FUEMAVND', 'FUESSV30', 'FUESSV50', 'FUESSVFL', 'FUETCC50', 'FUEVFVND', 'FUEVN100',
            'GAS', 'GDT', 'GEE', 'GEG', 'GEX', 'GIL', 'GMD', 'GMH', 'GSP', 'GTA', 'GVR', 'HAG', 'HAH', 'HAP',
            'HAR', 'HAS', 'HAX', 'HCD', 'HCM', 'HDB', 'HDC', 'HDG', 'HHP', 'HHS', 'HHV', 'HID', 'HII', 'HMC',
            'HNA', 'HPG', 'HPX', 'HQC', 'HRC', 'HSG', 'HSL', 'HT1', 'HTG', 'HTI', 'HTL', 'HTN', 'HTV', 'HU1',
            'HUB', 'HVH', 'HVN', 'HVX', 'ICT', 'IDI', 'IJC', 'ILB', 'IMP', 'ITC', 'ITD', 'JVC', 'KBC', 'KDC',
            'KDH', 'KHG', 'KHP', 'KMR', 'KOS', 'KPF', 'KSB', 'L10', 'LAF', 'LBM', 'LCG', 'LDG', 'LEC', 'LGC',
            'LGL', 'LHG', 'LIX', 'LM8', 'LPB', 'LSS', 'MBB', 'MCM', 'MCP', 'MDG', 'MHC', 'MIG', 'MSB', 'MSH',
            'MSN', 'MWG', 'NAB', 'NAF', 'NAV', 'NBB', 'NCT', 'NHA', 'NHH', 'NHT', 'NKG', 'NLG', 'NNC', 'NO1',
            'NSC', 'NT2', 'NTL', 'NVL', 'NVT', 'OCB', 'OGC', 'OPC', 'ORS', 'PAC', 'PAN', 'PC1', 'PDN', 'PDR',
            'PET', 'PGC', 'PGD', 'PGI', 'PGV', 'PHC', 'PHR', 'PIT', 'PJT', 'PLP', 'PLX', 'PMG', 'PNC', 'PNJ',
            'POW', 'PPC', 'PSH', 'PTB', 'PTC', 'PTL', 'PVD', 'PVP', 'PVT', 'QCG', 'QNP', 'RAL', 'RDP', 'REE',
            'RYG', 'S4A', 'SAB', 'SAM', 'SAV', 'SBA', 'SBG', 'SBT', 'SBV', 'SC5', 'SCR', 'SCS', 'SFC', 'SFG',
            'SFI', 'SGN', 'SGR', 'SGT', 'SHA', 'SHB', 'SHI', 'SHP', 'SIP', 'SJD', 'SJS', 'SKG', 'SMA', 'SMB',
            'SMC', 'SPM', 'SRC', 'SRF', 'SSB', 'SSC', 'SSI', 'ST8', 'STB', 'STG', 'STK', 'SVC', 'SVD', 'SVI',
            'SVT', 'SZC', 'SZL', 'TBC', 'TCB', 'TCD', 'TCH', 'TCI', 'TCL', 'TCM', 'TCO', 'TCR', 'TCT', 'TDC',
            'TDG', 'TDH', 'TDM', 'TDP', 'TDW', 'TEG', 'THG', 'TIP', 'TIX', 'TLD', 'TLG', 'TLH', 'TMP', 'TMS',
            'TMT', 'TN1', 'TNC', 'TNH', 'TNI', 'TNT', 'TPB', 'TPC', 'TRA', 'TRC', 'TSC', 'TTA', 'TTE', 'TTF',
            'TV2', 'TVB', 'TVS', 'TVT', 'TYA', 'UIC', 'VAF', 'VCA', 'VCB', 'VCF', 'VCG', 'VCI', 'VDP', 'VDS',
            'VFG', 'VGC', 'VHC', 'VHM', 'VIB', 'VIC', 'VID', 'VIP', 'VIX', 'VJC', 'VMD', 'VND', 'VNE', 'VNG',
            'VNL', 'VNM', 'VNS', 'VOS', 'VPB', 'VPD', 'VPG', 'VPH', 'VPI', 'VPS', 'VRC', 'VRE', 'VSC', 'VSH',
            'VSI', 'VTB', 'VTO', 'VTP', 'YBM', 'YEG']

HNXIndex = ['AAV', 'ADC', 'ALT', 'AMC', 'AME', 'AMV', 'API', 'APS', 'ARM', 'ATS', 'BAB', 'BAX', 'BBS', 'BCC',
            'BCF', 'BCH', 'BDB', 'BED', 'BKC', 'BNA', 'BPC', 'BSC', 'BST', 'BTS', 'BTW', 'BVS', 'BXH', 'C69',
            'CAG', 'CAN', 'CAP', 'CAR', 'CCR', 'CDN', 'CEO', 'CET', 'CIA', 'CJC', 'CKV', 'CLH', 'CLM', 'CMC',
            'CMS', 'CPC', 'CSC', 'CST', 'CTB', 'CTP', 'CTT', 'CVN', 'CX8', 'D11', 'DAD', 'DAE', 'DC2', 'DDG',
            'DHP', 'DHT', 'DIH', 'DL1', 'DNC', 'DNP', 'DP3', 'DS3', 'DST', 'DTC', 'DTD', 'DTG', 'DTK', 'DVM',
            'DXP', 'EBS', 'ECI', 'EID', 'EVS', 'FID', 'GDW', 'GIC', 'GKM', 'GLT', 'GMA', 'GMX', 'HAD', 'HAT',
            'HBS', 'HCC', 'HCT', 'HDA', 'HEV', 'HGM', 'HHC', 'HJS', 'HKT', 'HLC', 'HLD', 'HMH', 'HMR', 'HOM',
            'HTC', 'HUT', 'HVT', 'ICG', 'IDC', 'IDJ', 'IDV', 'INC', 'INN', 'IPA', 'ITQ', 'IVS', 'KDM', 'KHS',
            'KKC', 'KMT', 'KSD', 'KSF', 'KSQ', 'KST', 'KSV', 'KTS', 'L14', 'L18', 'L40', 'LAS', 'LBE', 'LCD',
            'LDP', 'LHC', 'LIG', 'MAC', 'MAS', 'MBG', 'MBS', 'MCC', 'MCF', 'MCO', 'MDC', 'MDD', 'MED', 'MEL',
            'MIC', 'MKV', 'MST', 'MVB', 'NAG', 'NAP', 'NBC', 'NBP', 'NBW', 'NDN', 'NDX', 'NET', 'NFC', 'NHC',
            'NRC', 'NSH', 'NST', 'NTH', 'NTP', 'NVB', 'OCH', 'ONE', 'PBP', 'PCE', 'PCG', 'PCH', 'PCT', 'PDB',
            'PEN', 'PGN', 'PGS', 'PGT', 'PHN', 'PIA', 'PIC', 'PJC', 'PLC', 'PMB', 'PMC', 'PMP', 'PMS', 'POT',
            'PPE', 'PPP', 'PPS', 'PPT', 'PPY', 'PRC', 'PRE', 'PSC', 'PSD', 'PSE', 'PSI', 'PSW', 'PTD', 'PTI',
            'PTS', 'PTX', 'PV2', 'PVB', 'PVC', 'PVG', 'PVI', 'PVS', 'PXK', 'QHD', 'QST', 'QTC', 'RCL', 'S55',
            'S99', 'SAF', 'SCG', 'SCI', 'SD5', 'SD9', 'SDA', 'SDC', 'SDG', 'SDN', 'SDU', 'SEB', 'SED', 'SFN',
            'SGC', 'SGD', 'SGH', 'SHE', 'SHN', 'SHS', 'SJ1', 'SJE', 'SLS', 'SMN', 'SMT', 'SPC', 'SPI', 'SRA',
            'SSM', 'STC', 'STP', 'SVN', 'SZB', 'TA9', 'TBX', 'TDT', 'TET', 'TFC', 'THB', 'THD', 'THS', 'THT',
            'TIG', 'TJC', 'TKU', 'TMB', 'TMC', 'TMX', 'TNG', 'TOT', 'TPH', 'TPP', 'TSB', 'TTC', 'TTH', 'TTL',
            'TTT', 'TV3', 'TV4', 'TVC', 'TVD', 'TXM', 'UNI', 'V12', 'V21', 'VBC', 'VC1', 'VC2', 'VC3', 'VC6',
            'VC7', 'VC9', 'VCC', 'VCM', 'VCS', 'VDL', 'VE1', 'VE3', 'VE4', 'VE8', 'VFS', 'VGP', 'VGS', 'VHE',
            'VHL', 'VIF', 'VIG', 'VIT', 'VLA', 'VMC', 'VMS', 'VNC', 'VNF', 'VNR', 'VNT', 'VSA', 'VSM', 'VTC',
            'VTH', 'VTJ', 'VTV', 'VTZ', 'WCS', 'WSS', 'X20']

print( set(VNINDEX) & set(HNXIndex) )
